### PR TITLE
Draft to add UI for Topics List 

### PR DESCRIPTION
**Pull request by suyash-naithani**
Signed-off-by: suyash-naithani <suyash.naithani@gmail.com>

Work done:

- Added view for table and search toolbar

- Added pagination and it's functionality

- Topics can be searched from the search input

In Progress

- We are currently getting data to populate the table from a file. We aim to get mock data from the Apollo server by providing it a schema and using a library such as faker. Any suggestions on setting up the mock server would be helpful

### CODE REVIEW

**Review by dlabaj — APPROVED** [review]
LGTM.  I'll move the the topics data into a graph ql query tomorrow and submit a review.

**Comment by dlabaj** [comment]
We can shut off the testing for now.

**Comment by pmuir** [comment]
@suyash-naithani looks like package.lock is out of sync...

**Comment by pmuir** [comment]
Replaced with #9

**Pull request closed without merging**
