### PR TITLE
Feat: add module federation

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
@dlabaj FYI

**Review by dlabaj — COMMENTED** [review]
Looks like the jest test needs to be updated for index.tsx

**Comment by pmuir** [comment]
@dlabaj fixed - i had done that upstream but forgot to add it here

**Comment by b1zzu** [comment]
Hi @pmuir @dlabaj, if it's ready can we get it merged? I would sync it to the midstream :)

**Comment by pmuir** [comment]
I don't have write access to this repo.

**Pull request merged**
